### ISSUE TITLE
Change does not last

### ISSUE THREAD

**Issue by lucashusted** [fniephaus/alfred-brightness#6]
On Catalina, I can adjust the brightness using your tool (min max, a particular percentage) and the screen brightness adjusts; however, after about 10 seconds, it goes back to where it was. If some change needs to be made to my settings to allow the new brightness to take effect, then please advise.

Thanks!

**Comment by sam-b-rose** [comment]
Experiencing the same issue 🙁

**Comment by fniephaus** [comment]
Is it possible that you have the "Automatically adjust brightness" option enabled in your preferences?
<img width="668" alt="image" src="https://user-images.githubusercontent.com/2368856/104429264-b627b900-5585-11eb-8a2e-077894ce73cf.png">

**Comment by fniephaus** [comment]
Please feel free to re-open if the problem persists.

**Comment by tcheymol** [comment]
Actually, I experience the same problem, and the "Auto Ajust brightness" setting is set to false (I am on Big Sur however)
